require_relative "./zzounds_deals/version"
require_relative "./zzounds_deals/cli"
require_relative "./zzounds_deals/scraper"
require_relative "./zzounds_deals/deal"
require "nokogiri"
require "open-uri"
require "pry"